trigger: none
pr: none


resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '3e83a24b-581f-4a2a-8dce-2e885f216a4e'
  imageRepository: 'ahsimplegorepo'
  containerRegistry: 'raireg1.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'raireg15cfe-auth'


stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build  
    steps:
    - task: Docker@2
      displayName: Build and push an image to ACR
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        tags: '$(tag)'
