trigger: none
pr: none


resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '310e6edb-7ad3-4a6a-8b82-137112b9eded'
  imageRepository: 'zenithworksahsimplegorepo'
  containerRegistry: 'raireg3.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'raireg212056e58-auth'


stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build  
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        tags: '$(tag)'
